# Generated by Django 2.2.5 on 2019-09-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miles_app', '0002_auto_20190923_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miles',
            old_name='miles_driven',
            new_name='total_miles',
        ),
    ]
